name: Python application
on: 
  push:
    branches: 
    - master
  schedule:
  - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: runapp
      run: |
        python main.py
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: yiqin
        # Git branch where assets will be deployed
        target_branch: # optional, default is gh-pages
        # Create incremental commit instead of doing push force
        keep_history: # optional, default is false
        # Allow an empty commit to be created
        allow_empty_commit: # optional, default is true
        # Build directory to deploy
        build_dir: dists
        # Commit author's name
        committer_name: robots # optional
        # Commit author's email
        committer_email: laomocode@gmail.com # optional
        # Commit message
        commit_message: New update # optional
        # Write the given domain name to the CNAME file
        fqdn: wuhan.zw2s.ltd # optional
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
